* Server - Database - Table

#### 1. SELECT: 데이터 조회
**`SELECT`** columns (or *)

**`FROM`** table_name

#### 2. DISTINCT: 중복제거
**`SELECT` DISTINCT(columns)**

**`FROM`** table_name

#### 3. WHERE: 조건검색
**`SELECT`** COUNT(DISTINCT(column))

**`FROM`** table_name

**`WHERE`** conditions

- 파이썬과 다른점은 equal이 '=='가 아닌 '='로 해도 된다는 점
- **BETWEEN A AND B** (A, B값도 포함)

    **`SELECT`** *

    **`FROM`** table_name

    **`WHERE`** column **BETWEEN A AND B**

#### 4. ORDER BY:정렬
**`SELECT`** *

**`FROM`** table_name

**`ORDER BY`** column **ASC** 

**`ORDER BY`** column1, column2 **ASC** : column1에 대해 정렬하고, 그 다음 2에 대해 정렬


- ASC: 오름차순(dafault)
- DESC: 내림차순

#### 5. CONCAT: column데이터 합치기
**`SELECT`** column1, **CONCAT(col2, col3) as col23** : col2와 col3을 합쳐줌

**`FROM`** table_name

#### 6. LIKE: where절에서 특정 문자열이 들어간 데이터 조회
**`SELECT`** *

**`FROM`** table_name

**`WHERE`** column **LIKE** "%p%" : 문자열 p가 들어가는 데이터 조회


#### 7. IN: 여러개의 조건을 조회할 때 사용
**`SELECT`** *

**`FROM`** table_name

**`WHERE`** column **IN** ('a', 'b', 'c'): column에서  a, b, c인 데이터 줄력


#### 8. LIMIT: 데이터 수 제한

**`SELECT`** *

**`FROM`** table_name

**`LIMIT`** 3 : 상단의 데이터 3개 출력

**`LIMIT`** 3, 5 : 인덱스 3인 데이터부터 5개 출력

#### 9. UPDATE
**`UPDATE`** table_name

**`SET`** column=a

**`WHERE`** condition
:condition에 부합하는 데이터 를 column=a로 업데이트

#### 10. GROUP BY

- city 테이블에서 나라별 도시의 개수를 출력
```
SELECT CountryCode, COUNT(CountryCode) AS count
FROM city
GROUP BY countryCode; # 중복데이터 삭제
```
- countrylanguage 테이블에서 전체 언어의 개수츨 출력
```
SELECT count(distinct(LANGUAGE))
from countrylanguage;
```
- 대륙별 인구수와 GNP의 최댓값을 출력
```
SELECT continent, sum(population), max(GNP), SUM(GNP)/SUM(population)
FROM country
GROUP BY continent;
```
- 대륙별 전체인구를 구하고 5억 이상인 대륙만 출력
- Having: group by가 실행되고 난 결과에 조건을 추가
- Where: group by 하기 전의 데이터 필터링
```
SELECT Continent, SUM(Population) AS data
FROM country
GROUP BY continent
-- WHERE data >= 500000000;  이렇게 쓰면 오류가 난다
HAVING DATA > 500000000;
```